### ISSUE TITLE
Verlinkungen und (Link-)Anker im Dokument

### ISSUE THREAD

**Issue by fabianlemmes** [ckoeppl/MALIS-20.3-WPM_T9.1#3]
Liebe Chantal,

nachfolgend eine erste Rückmeldung, in Sachen ...

### Verlinkungen:

Ich würde (teilweise) die **Link-Anker** anders setzen/benennen, z.B.

**Z. 7:** Statt

> [...] einzelne Normdateien [zusammengeführt](https://prezi.com/p/i86nojr2q6rs/geschichte-der-gnd/).

so etwas wie:

> In ihr wurden 2012 vier vorher bestehende, einzelne Normdateien zusammengeführt ([Geschichte der GND](https://prezi.com/p/i86nojr2q6rs/geschichte-der-gnd/)).

Ähnlich:

**Z. 28:** Statt

> [...] BASE ([Ein Jahr Claiming-Service in der Deutschen Nationalbibliografie mit GND](https://www.orcid-de.org/claiming-service-gnd-orcid/)).

lieber so etwas wie

> [...] BASE (siehe [ORCID DE-Blog](https://www.orcid-de.org/claiming-service-gnd-orcid/), Eintrag vom 5. August 2020).

**Z. 39:** Statt

> [...] "GND-Toolbox" entwickelt ([Das Projekt "GND für Kulturdaten" (GND4C)](https://www.o-bib.de/article/view/5539/7880), S. 67ff.).

würde ich als Link-Anker, da Du ja auch die exakte Seite des Artikels zitierst, die bibliogr. Angabe, ggf. in Kurzform, hernehmen; z.B. also

> [...] "GND-Toolbox" entwickelt (vgl. [Kett et al. 2019](https://www.o-bib.de/article/view/5539/7880), S. 67ff.).

Weiterführende Anmerkung: "ff." soll man nicht hernehmen, habe ich gelernt; entweder den exakten Seitenbereich angeben od. ggf. so etwas wie "S. 67 und passim" (= im Weiteren, im Allgemeinen).

Abschließend: Du könntest **Z. 17** noch einen Link zur Website der AEN-Abteilung einfügen, falls es eine solche gibt ...?

***Das Ganze ist natürlich zum großen Teil aber auch persönliche Geschmackssache und macht es (aus dieser Perspektive) nicht besser und nicht schlechter ... Dennoch glaube ich, dass das Dokument von dieser Überarbeitung profitieren wird.***

### Weiteres zum Thema Anker:

In **Z. 17** referenzierst Du intern auf Punkt 3 in Deiner Darstellung. Vielleicht könntest Du da so einen schönen "#"-Anker setzen, um an die entsprechende Stelle im Dokument zu verlinken (NB: Ich glaube, das kann nicht jede MD-Engine ...)?

**Comment by ckoeppl** [comment]
Lieber Fabian,

vielen Dank für deine vielen konkreten und völlig richtigen Anmerkungen! Zum größten Teil habe ich diese bereits übernommen. Nur eine Sache bereitet mir gerade noch Schwierigkeiten und ich frage mich, ob Du hier möglicherweise noch Hilfestellung geben könntest?

> In Z. 17 referenzierst Du intern auf Punkt 3 in Deiner Darstellung. Vielleicht könntest Du da so einen schönen "#"-Anker setzen, um an die entsprechende Stelle im Dokument zu verlinken [...]?

Ich habe auf verschiedenen Seiten nachgesehen und festgestellt, dass Header-Anker wohl wie Links im Stil [Link](#ankername) angelegt werden. Konkret habe ich dies so umgesetzt: 

> \[Punkt 3](#-3.-erschließung-und-verknüpfung-von-normdaten)

Leider komme ich damit nicht weiter. Hast Du eine Idee und könntest mir womöglich sogar direkt einen Vorschlag machen, wenn du heute deine Pull Request loslässt?

**Comment by fabianlemmes** [comment]
Liebe Chantal,

folgende Syntax scheint hier (und z.B. auch im HedgeDoc) zu funktionieren:

Link-Anker im Text:

`[beliebiger_Link-Name](#korrespondierende_Link-ID)`

Stelle, auf die Du verlinken möchtest:

`### <a id="korrespondierende_Link-ID"></a>3. Erschließung und Verknüpfung von Normdaten`

Was anscheinend auch funktioniert (und syntaktisch ein bisschen schöner ist, da öffnendes und schließendes Tag die Überschrift "einrahmen"):

`### <a id="korrespondierende_Link-ID">3. Erschließung und Verknüpfung von Normdaten</a>`

(... Und so versteht dann auch *Notepad++* die Anweisung; das hat nämlich mit der oberen Variante *dort* nicht funktioniert ...)


Was man so liest, handhaben verschiedene Plattformen das Ganze jeweils ein bisschen unterschiedlich (siehe z.B. die Diskussion auf https://stackoverflow.com/questions/6695439/how-to-link-to-a-named-anchor-in-multimarkdown). Die Variante mit dem Attribut `name=` statt `id=` funktioniert hier auf GitHub (und auch auf HedgeDoc) anscheinend schon einmal nicht ...

Ich übernehme das Ganze gern im Request und baue den Code entsprechend ein; Du kannst es ja dann dort noch einmal nachvollziehen (und ggf. auch noch einmal verändern ...)!

**Comment by ckoeppl** [comment]
Tausend Dank für deine Hilfe! Es hat nun funktioniert. 😄  🙏 

Viel Erfolg für deine Textproduktion!
