### ISSUE TITLE
Verschiedene Rückfragen

### ISSUE THREAD

**Issue by fabianlemmes** [ckoeppl/MALIS-20.3-WPM_T9.1#4]
Liebe Chantal,

beim Durcharbeiten des Dokuments haben sich bei mir zudem verschiedene (Verständnis-)Rückfragen ergeben:

**Z. 11 (Typ: `<!---QUESTION -->`):**

> [...] Auswahl von Themenbereichen und von insgesamt **sieben** mit ihnen verknüpften Prozessen.

Ich zähle nur sechs ...?

**Z. 17 (Typ: `<!---QUESTION -->`):**
> [...] Beschlagwortung [...]

Habe ich noch nie gehört ...? Doch google lehrt mich: Den Begriff gibt es als Parallelform zur bekannt(er)en (?) "Verschlagwortung" ...

**Ebd. (Typ: `<!---COMMENT -->`):** Ich meine, "Tables of Content" müsste es trotz allem heißen, und nicht

> Tables of Content**s**

**Z. 22 (Typ: `<!---COMMENT -->`):**

> [...] eine heterogene, inkonsistente Datenlage bzw. Erfassungslage zur Folge, die nur nach und nach **-** in progress **-** bereinigt wird.

Nach den Regeln der (Typographen-)Kunst müsste hier m.E. eigentlich jeweils ein *Halbgeviertstrich* "–" hin, und kein *Divis* "-".

Du findest jenen in der Windows-Zeichentabelle (ansteuerbar z.B. über "Windows-Taste" + ".") unter Symbole = das Majuskel-Omega "Ω", links unter Allg. Interpunktionszeichen = "<".

**Z. 40 (Typ: `<!---QUESTION -->`):**

Du schreibst

> " [...] entlasten, als die maschinell erkannten Dubletten unmittelbar [...]".

Das Wörtchen "als" erschließt sich mir an dieser Stelle vom Sinn her bzw. syntaktisch nicht ...

---

So, das war's nun aber erst einmal im Großen und Ganzen!

Im nächsten und vermutlich letzten Workaround korrigiere ich (stillschweigend) noch ein paar wenige orthographische Sachen und Tippfehler, dann habe ich nichts mehr zu kritisieren ... 😉

**Comment by ckoeppl** [comment]
Lieber Fabian,

> Z. 11 (Typ: \):
> 
> [...] Auswahl von Themenbereichen und von insgesamt sieben mit ihnen verknüpften Prozessen.
> 
> Ich zähle nur sechs ...?

Stimmt! Ganz ursprünglich waren es mal acht Prozesse, aber da ich schon mit den bestehenden sechs Prozessen die Wortzahl ausgereizt habe,... 
Danke für das aufmerksame Lesen!

> Z. 17 (Typ: \):
>
> [...] Beschlagwortung [...]
>
> Habe ich noch nie gehört ...? Doch google lehrt mich: Den Begriff gibt es als Parallelform zur bekannt(er)en (?) "Verschlagwortung" ...

Mir ging es ganz ähnlich, doch habe ich den Begriff so von von der Abteilung AEN übernommen und auf seine Richtigkeit vertraut.

Auch mit den übrigen Kommentaren hast du natürlich völlig Recht. Ich gehe daher nicht im Einzelnen auf sie ein.

Nun bin ich gespannt auf deine Pull Request! 👏

**Comment by fabianlemmes** [comment]
Liebe Chantal,

vielen Dank für Deine Erläuterungen! Request geht der Vervollständigung entgegen ...!

(Das Issue kannst Du auch gern schließen ... Oder nein: Ich kann das auch. Bin so frei ...)

Herzliche Grüße, Fabian
